-- 코드를 입력하세요
SELECT H.HISTORY_ID
        , CASE
            WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 7
                && DATEDIFF(H.END_DATE, H.START_DATE) + 1 < 30
                THEN TRUNCATE(C.DAILY_FEE * (DATEDIFF(H.END_DATE, H.START_DATE) + 1) * 0.95, 0)
            WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 30
                && DATEDIFF(H.END_DATE, H.START_DATE) + 1 < 90
                THEN TRUNCATE(C.DAILY_FEE * (DATEDIFF(H.END_DATE, H.START_DATE) + 1) * 0.92, 0)
            WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 90
                THEN TRUNCATE(C.DAILY_FEE * (DATEDIFF(H.END_DATE, H.START_DATE) + 1) * 0.85, 0)
            ELSE
                TRUNCATE(C.DAILY_FEE * (DATEDIFF(H.END_DATE, H.START_DATE) + 1), 0)
        END AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
ON C.CAR_ID = H.CAR_ID
WHERE C.CAR_TYPE = '트럭'
GROUP BY H.HISTORY_ID
ORDER BY FEE DESC, H.HISTORY_ID DESC