-- 코드를 입력하세요
SELECT J.FLAVOR
FROM FIRST_HALF F
INNER JOIN JULY J
ON J.FLAVOR = F.FLAVOR
GROUP BY J.FLAVOR
ORDER BY SUM(J.TOTAL_ORDER + F.TOTAL_ORDER) DESC
LIMIT 3

# SELECT *
# FROM FIRST_HALF F
# LEFT JOIN JULY J
# ON J.FLAVOR = F.FLAVOR